
name: Metrics Dashboard

on:
  schedule:
    - cron: "0 6 * * *"   # daily
  workflow_dispatch:

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: iamapsrajput
          template: classic
          filename: metrics.svg
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Warsaw
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_stars: yes
          plugin_followup: yes
          output_action: commit
