
name: Profile Summary Cards

on:
  schedule:
    - cron: "0 3 * * *"   # daily
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate cards
        uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: iamapsrajput
          UTC_OFFSET: "+2"   # Europe/Warsaw
          AUTO_PUSH: "true"
